updated host name for docker postgres

diff --git a/.github/workflows/ci_pipeline.yml b/.github/workflows/ci_pipeline.yml
--- a/.github/workflows/ci_pipeline.yml
+++ b/.github/workflows/ci_pipeline.yml
@@ -36,13 +36,16 @@ jobs:
       - name: Wait for PostgreSQL to be Ready
         run: |
           echo "Waiting for PostgreSQL..."
-          until docker exec $(docker ps -q -f name=postgres) pg_isready -U postgres; do
+          CONTAINER_ID=$(docker ps --filter "name=pgduckdb" --format "{{.ID}}")
+
+          if [ -z "$CONTAINER_ID" ]; then
+            echo "Error: PostgreSQL container not found!"
+            docker ps
+            exit 1
+          fi
+
+          until docker exec "$CONTAINER_ID" pg_isready -U postgres; do
             sleep 3
           done
+
           echo "PostgreSQL is ready!"
-
-      - name: Run Tests
-        run: make test
-
-      - name: Stop Docker Compose
-        run: docker compose down
